### ISSUE TITLE
Unclear License

### ISSUE THREAD

**Issue by DavZim** [yihui/mime#19]
Similar to #7 but different;

In the DESCRIPTION file, the package is licensed under "GPL" without specifying v2, >=v2, or v3.
According to https://cran.r-project.org/web/licenses/ and https://svn.r-project.org/R/trunk/share/licenses/license.db it should be either GPL v2 or GPL v3.

Is it maybe possible to add which version the package is distributed under?

Thank you!

**Comment by yihui** [comment]
Either version is okay: https://cran.r-project.org/package=mime

If that's too much trouble for you, I can consider relicensing this package to MIT.

**Comment by DavZim** [comment]
Thank you for the quick reply, I wasn't aware that GPL is automatically expanded to GPL v2|v3, that solves the issue for me.
There is no need to relicense the package to MIT from my side.
